# Generated by Django 4.2.1 on 2023-09-15 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_blog_blog_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_slug',
            field=models.SlugField(blank=True, default='', editable=False, unique=True, verbose_name='auto_generated_slug'),
        ),
    ]
