# Generated by Django 4.2.1 on 2023-09-21 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0006_alter_blog_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='commentuser',
            name='name',
        ),
        migrations.RemoveField(
            model_name='commentuser',
            name='ratings',
        ),
        migrations.AddField(
            model_name='commentuser',
            name='img',
            field=models.ImageField(null=True, upload_to='comment_user_img'),
        ),
        migrations.AddField(
            model_name='commentuser',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blogsubimg',
            name='sub_img1',
            field=models.ImageField(blank=True, upload_to='sub_blog_img'),
        ),
        migrations.AlterField(
            model_name='blogsubimg',
            name='sub_img2',
            field=models.ImageField(blank=True, upload_to='sub_blog_img'),
        ),
        migrations.AlterField(
            model_name='blogsubimg',
            name='sub_img3',
            field=models.ImageField(blank=True, upload_to='sub_blog_img'),
        ),
        migrations.RemoveField(
            model_name='likes',
            name='user',
        ),
        migrations.AddField(
            model_name='likes',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='like_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
